server.port=8080

spring.datasource.url=jdbc:h2:tcp://h2-566022:1521/nexusverde
spring.datasource.username=carlos
spring.datasource.password=fiapcloud
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=false