server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:tcp://H2Sprint:1521//opt/h2-data/test}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:carlos}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fiapcloud}

spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=false