# Configurações do servidor
server.port=8080


# Configurações do H2
spring.datasource.url=jdbc:h2:tcp://H2Sprint:1521/test
spring.datasource.username=carlos
spring.datasource.password=fiapcloud
spring.datasource.driver-class-name=org.h2.Driver


# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true


# Configurações de inicialização do banco
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# Configurações do H2 Console
spring.h2.console.enabled=false


# Configurações de logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE